name: check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      with:
          fetch-depth: 0

      - name: Install npm deps
        run: npm install

      - name: Tests
        run: npm run test

      -name: Lint
        run: npm run lint
